export const ACTION_TYPE = {
	ADD_POST: 'ADD_POST',
	UPDATE_POST: 'UPDATE_POST',
	DELETE_POST: 'DELETE_POST',
	LOAD_TESTS: 'LOAD_TESTS',
	LOAD_REQUESTED: 'LOAD_REQUESTED',
	TESTS_REQUESTED_FAILED: 'TESTS_REQUESTED_FAILED',
};
